server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
#设置feign客户端超时时间
ribbon:
  #指的是建立连接用的时间,适用于网络延迟正常的情况下,两端连接所用的时间
  ReadTimeout:  5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

spring:
  application:
    name: cloud-provider-hystrix-order

feign:
  hystrix:
    enabled: true
